"""profile fields, preferences, resume file metadata

Revision ID: 72c74bb5b6e2
Revises: bcf52285a161
Create Date: 2026-09-05 15:00:58.018012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72c74bb5b6e2'
down_revision: Union[str, Sequence[str], None] = 'bcf52285a161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('preferred_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('experience_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('remote_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('employment_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('min_match_score', sa.Integer(), nullable=False),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('posted_within_days', sa.Integer(), nullable=False),
    sa.Column('include_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exclude_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preferences_profile_id'), 'preferences', ['profile_id'], unique=False)
    op.add_column('profiles', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('state', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('country', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('university', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('cgpa', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('skills_programming', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('profiles', sa.Column('skills_frameworks', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('profiles', sa.Column('skills_databases', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('profiles', sa.Column('skills_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('profiles', sa.Column('skills_other', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('resumes', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('resumes', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('resumes', sa.Column('content_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'content_type')
    op.drop_column('resumes', 'file_size')
    op.drop_column('resumes', 'file_name')
    op.drop_column('profiles', 'skills_other')
    op.drop_column('profiles', 'skills_tools')
    op.drop_column('profiles', 'skills_databases')
    op.drop_column('profiles', 'skills_frameworks')
    op.drop_column('profiles', 'skills_programming')
    op.drop_column('profiles', 'cgpa')
    op.drop_column('profiles', 'university')
    op.drop_column('profiles', 'country')
    op.drop_column('profiles', 'state')
    op.drop_column('profiles', 'city')
    op.drop_index(op.f('ix_preferences_profile_id'), table_name='preferences')
    op.drop_table('preferences')
    # ### end Alembic commands ###
