"""align_execution_locks_model_with_no_fks

Revision ID: 8d76a95b1b4f
Revises: 4fe428962347
Create Date: 2026-09-10 23:54:51.354809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d76a95b1b4f'
down_revision: Union[str, Sequence[str], None] = '4fe428962347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_executions_idempotency_key'), table_name='application_executions')
    op.create_index(op.f('ix_application_executions_idempotency_key'), 'application_executions', ['idempotency_key'], unique=True)
    op.drop_index(op.f('ix_execution_locks_owner'), table_name='execution_locks')
    op.drop_index(op.f('ix_execution_locks_package'), table_name='execution_locks')
    op.drop_constraint(op.f('uq_execution_locks_package'), 'execution_locks', type_='unique')
    op.create_index(op.f('ix_execution_locks_package_id'), 'execution_locks', ['package_id'], unique=True)
    op.drop_constraint(op.f('execution_locks_execution_id_fkey'), 'execution_locks', type_='foreignkey')
    op.drop_constraint(op.f('execution_locks_package_id_fkey'), 'execution_locks', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('execution_locks_package_id_fkey'), 'execution_locks', 'application_packages', ['package_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('execution_locks_execution_id_fkey'), 'execution_locks', 'application_executions', ['execution_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_execution_locks_package_id'), table_name='execution_locks')
    op.create_unique_constraint(op.f('uq_execution_locks_package'), 'execution_locks', ['package_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_execution_locks_package'), 'execution_locks', ['package_id'], unique=False)
    op.create_index(op.f('ix_execution_locks_owner'), 'execution_locks', ['owner_id'], unique=False)
    op.drop_index(op.f('ix_application_executions_idempotency_key'), table_name='application_executions')
    op.create_index(op.f('ix_executions_idempotency_key'), 'application_executions', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###
